# basic options 
title: uxsys
author: kimy747
email: kimy747@uxsys.com
description: a wonderful site 

# Build settings 
markdown: karmadown 
#theme: jekyll-theme-time-machine
#theme: jekyll-theme-dinky
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-cayman